platform:ios, ‘8.0’

target 'TheProjectFrameWork' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MBProgressHUD', '~> 0.8'
    pod 'Reachability', '~> 3.2'
    pod 'SDCycleScrollView'
    pod 'Masonry'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'GTSDK', '2.3.1.0-noidfa'
end








